---
title: References for spoken similarity search
bibliography: refs.bib
---

## [Billion-Scale Similarity Search with GPUs](https://www.computer.org/csdl/journal/bd/2021/03/08733051/1aFvgKKpjoc) [@Johnson2021billion]
- [arXiv](https://arxiv.org/abs/1702.08734)
- MSEB: "we adopted a cascade encoding approach, which remains the state-of-the-art for current industrial voice search systems"
- Paper does not mention cascade encoding, or even voice; only images search

## [Searching in one billion vectors: Re-rank with source coding](https://ieeexplore.ieee.org/document/5946540) [@jegou2011searching]
- Related to [@Johnson2021billion]
- cites [@jegou2011product]

## [Product Quantization for Nearest Neighbor Search](https://ieeexplore.ieee.org/document/5432202) [@jegou2011product]
- Introduces IVFADC, which is a combination of an inverted file system (IVF) and asymmetric product quantization (ADC).
> The idea is to decompose the space into a Cartesian product of low-dimensional subspaces and to quantize each subspace separately.
> A vector is represented by a short code composed of its subspace quantization indices.
