---
title: "KBLabb notes"
bibliography: refs.bib
---

### [Swedish Sentence Transformer 2.0](https://kb-labb.github.io/posts/2023-01-16-sentence-transformer-20/) [@rekathati2023]

- SweParaphrase v1.0
  - Pearson 0.9283 (best model)
- SweParaphrase v2.0
  - v1.1 best
- SweFAQ v2.0
  - retrieval task
  - train: 0.7106
  - dev: 0.6727
  - test: 0.5871

### [Swedish Bootleg model](https://kb-labb.github.io/posts/2022-03-03-swedish-bootleg-model/) [@fano2022]
- Based on [Bootleg](https://github.com/HazyResearch/bootleg) [@orr2020bootlegchasingtailselfsupervised]
- Nothing released

### [For how long is a person recognisable by their voice?](https://kb-labb.github.io/posts/2023-07-04-for-how-long-is-a-person-recognisable-by-their-voice/)
- [code](https://github.com/MKNachesa/masters_thesis)
- [thesis](https://uu.diva-portal.org/smash/record.jsf?pid=diva2%3A1762445&dswid=-1452)

### [Finding Speeches in the Riksdag’s Debates](https://kb-labb.github.io/posts/2023-02-15-finding-speeches-in-the-riksdags-debates/) [@rekathati2023]
- [code](https://github.com/kb-labb/riksdagen_anforanden) --- no licence
- [data](https://github.com/kb-labb/riksdagen_anforanden/tree/main/metadata)

### [Welcome KB-Whisper, a new fine-tuned Swedish Whisper model!](https://kb-labb.github.io/posts/2025-03-07-welcome-KB-Whisper/) [@vesterbacka2025]
- [Hugging face collection](https://huggingface.co/collections/KBLab/kb-whisper)
- [notebook](https://colab.research.google.com/drive/1RCP53jqClJz0zDX_VBT_K04BevUKk842?usp=sharing)

### [RixVox: A Swedish Speech Corpus with 5500 Hours of Speech from Parliamentary Debates](https://kb-labb.github.io/posts/2023-03-09-rixvox-a-swedish-speech-corpus/) [@rekathati2023rixvox]
- [dataset](https://huggingface.co/datasets/KBLab/rixvox)


### [Swedish speech synthesis](https://kb-labb.github.io/posts/2023-05-24-swedish-text-to-speech/) [@rekathati2023tts]
- Uses Piper
- [voice weights](https://rhasspy.github.io/piper-samples/)
- `wget https://github.com/rhasspy/piper/releases/download/v0.0.2/voice-sv-se-nst-medium.tar.gz`
- [Hugging face](https://huggingface.co/KBLab/piper-tts-nst-swedish)
- Uses the (now deleted) [NST Martin data](https://www.nb.no/sprakbanken/en/resource-catalogue/oai-nb-no-sbr-18/)

### [CLIP-Topic: Identifying Themes in Large Image Collections](https://kb-labb.github.io/posts/2025-12-01-clip-topic/)
- [notebook](https://colab.research.google.com/drive/1CMJ0ko8kWA4Zjf_qkBA0AN_TwDHeRV8t?usp)
