---
title: "Irish thing"
abstract: |
  
bibliography: refs.bib
---

::: {.callout-note}
The basic idea of this is to present the idea of using Universal Dependencies conllu files
as the basis for derived text *and* audio; further, looking at Irish examples, there
are needs to repair standardisation to match dialectal speech.
:::

One complication posed by Irish is that the standard language is exclusively a written one:
there are three primary dialects of spoken Irish, which all have differences in terms of
grammar and vocabulary.

::: {.callout-note}
What problem am I trying to solve?
:::

- data
  - not enough
  - little open licensed
  - what exists does not represent the speech of natives: Common Voice, FLORES, yodas2

Multilingual ASR exists, but does not perform well: non-native speech dominates, 

In text oriented fields, a number of solutions exist to share annotations independently of the
text. As the input data for speech technologies such as ASR and TTS depend on text as well as
speech, we propose to adapt and extend an existing mechanism from just text to text and audio
pairs.

[[ Here a link to some UD treebank that does this would be fantastic ]]


[[ In the field of NLP, much thought has already been given to this problem...]]



