channels:
  - conda-forge
dependencies:
  - datasets>=2.20
  - numpy>=1.24
  - pip
  - pynini>=2.1.5
  - pytest
  - python=3.10
  - pyyaml>=6.0
  - pytorch>=2.0
  - torchaudio>=2.0
  - transformers>=4.30
