---
title: "Multilingual G2P — old ByT5/pivot draft (junk)"
bibliography: references.bib
---

## Introduction

<!-- This is meant to be garbage so it will infuriate me into rewriting, but the point is to get my thoughts slightly in order -->

Grapheme-to-phoneme is typically considered in terms of a single language, but languages do not exist in isolation: words, and particularly names, from other languages make frequent appearances.

<!-- SSML etc.? -->

In a rule-based paradigm, there are two common options for adapting a system designed for one language to the phoneset of another: either by editing the G2P rules themselves so that they output phones appropriate for the second language, or by explicitly mapping the phones it outputs to those of the other language.

Pivots (or bridge languages) have long been used in machine translation to augment lexicons in rule-based machine translation [@forcada2011apertium], or phrase tables in statistical machine translation [@kumar-etal-2007-improving; @CHEN08.733].

<!-- Is it worth going further into the background around vector space word representations? Like, word2vec itself, but there was also a multilingual followup that lays the basis for... well, for my assertion that the Google NMT people knew they were going to get zero shot translation. There was other work in at least search for years before that: it's taken as given now that Mikolov demonstrated that words clustered in high dimensional spaces, but this was known and the explicit task he trained for demonstrates that; but what word2vec gave was that when the classifier was discarded, the embeddings learned in the model gave the possibility of analogy queries. -->
<!-- tf/idf, latent semantic analysis, semantic vector space models -->

Google's Neural Machine Translation [@johnson-etal-2017-googles] learned an implicit pivot through the use of a single set of shared modules with a prepended token to signify target language, the alignments tended to converge in a space akin to an interlingua. In addition to improving performance among less resourced language pairs, they found that "zero-shot" translation became possible for language pairs that weren't seen in training, but for which a pivot was available.

<!-- Need to say something about T5, because it's a key step -->
<!-- That is: the artificial token is a precursor to the kinds of prompts used in T5, but it broadly equivalent to using the same kind of token when concatenating FSTs. -->

In this work, we attempt to use a combination of data selection and task prompting to guide a (by)T5 model, which has already been shown to perform well at the G2P task, towards being able to produce phonetic transcriptions of words from one language using the phoneset of another with minimal intervention.

<!-- "minimal intervention", yuck. It's G2P, not a UN peacekeeping mission -->

<!-- charsiu g2p just uses a language prefix -->
<!-- doing something similar... `g2p|lang=sv` extended to `g2p|lang=sv|from=en` etc. -->

<!-- Research question: Is the prompt going to be enough? In a full text system, there's enough context-based information to learn degrees of synonymity, the broad equivalents of parts of speech, etc. The prompt alone is enough to introduce sufficient context to know that a different set of outputs are expected, but it's not necessarily the case that it will be sufficient to align the 'from=X' to monolingual 'lang=X'; having an explicit second task, 'ipa2ipa|from=X|to=Y' is how I intended to overcome that, an explicit pivot. Testing this is what I'm stuck on: are both needed? -->

<!-- JE: In many cases, there will be zero conceivable way to find whether, say, "Olsen" is to be pronounced Swedish-like, Danish-like, or English-like in a Swedish sentence. There is a really realy good bet to make (and it really isn't Danish-like), but if the context (or some other situational evidence) tells us that we're talking about the surname of those annoying US brat twins... What I mean is that a word (in particular name) may look _very much_ like lang X, and in lang Y you may want to make that lang-y-ified lang X or something. But it can be full-blown age-old lang-Y in any case. Or any mix of the two, So... being permitted labels I think is good. Now. I still get confused when I try to understand when the labels are to be used and how... -->

<!-- JOR: the base case I'm looking at, if everything else fails, is of a mechanism that can be plugged into the text processing layer of a TTS system that can be **specifically** told 'X is an English word, pronounce it as a Swede would'; what I'm betting on is that giving a model with T5-level expressivity an explicit pivot can cut down on the amount of explicit data needed to achieve _that_ task in an otherwise multilingually trained G2P system. -->

<!-- NB!!! (JE, supervisor) but regardless. The actual things that will happen in the paper needs to start making their way into the text _now_, at the very least as bullets. Spend less times with the thing you don't know how they will happen, until you've spent a little time on the things _you know_ will happen. Please. -->

<!-- Swearing here because I need to be less.... contentious -->
<!-- More broadly, G2P has been beset from all sides by a pack of... people who don't understand the basic problem beyond something they can chuck a transformer at. The basic notion of "zero shot G2P" is breathtakingly idiotic to the extent that I would need to reach beyond the confines of monolingual expression in English to adequately summarise how I think of it. Yeah, awesome, you can produce some random IPA string for a language you don't know. Cool story bro, needs dragons and stuff. -->

<!-- A non-goal for this work is the kind of "zero shot" G2P claimed in @zhu22_interspeech. Although it does seem, as they claim, to be a useful basis for future G2P models for under-resourced languages, we consider the concrete case of G2P as a component of a text-to-speech system which must, as a result of human limitations, be bounded to the phoneme inventory of the speaker. Our intention, rather, is to prime the G2P system through data- and task-selection to produce something that is within the speaker's range, and hopefully broadly representative of how a speaker of one language pronounces loanwords from another. -->

<!-- "Zero shot" is a catchy buzzword, but its use by @zhu22_interspeech is unconvincing: that they produce some kind of IPA string for an "unknown" language whose vocabulary consists of randomly selected words from other languages is not in question; that the result of this serves any purpose is. -->
<!-- JE (supervisor): I agree fully. -->

## Background & related work

## Method

<!-- JE (supervisor): Is this similar to what we should do or no? -->

- Start from a pretrained multilingual T5 model (byT5; the Charsiu paper muddies the waters by having some that they pre-trained themselves, and being vague about which ones are fully trained and which are merely fine-tuned)

- Introduce a light adaptation step: teach the model to map words to phonemes using simple prompts (`g2p|lang=sv: word`)
  - Use small language-specific G2P datasets for that alignment.

- Probe implicit behaviour: remove the explicit `lang=` cue and test whether the model infers target phones from the text alone.
  <!-- Not the use case I'm interested in. Fundamentally, what is this useful for? The issue I take with the "zero shot" nonsense in charsiu is that it's not actually useful. -->
  <!-- JE (supervisor): Good. -->

- **I want to be quite specific about targeting G2P for *foreign* words.**

- It becomes useful after the next step to see to what extent the `from=X` part can be removed, so there's some equivalence in terms of needing to probe, but it comes later. Basic monolingual G2P is a baseline task, and it's foundational, but I'm not interested in it for its own sake.

- Introduce specific vocabulary that is additionally tagged with the donor language: `g2p|lang=sv|from=en`. The equivalent SSML would be:

```xml
<speak xml:lang="sv-SE">
  Jag ser fram emot <lang xml:lang="en-US">weekend</lang>!
</speak>
```

- Probably for Swedish it would also be beneficial to introduce a compound splitting task, because the 'sch' in dusch is not the same as in potatischips.
  <!-- JE (supervisor): Honestly it makes little (as in "not none at all") sense to do that within the G2P task. It really is better dealt with as preprocessing. For a whole slew of reasons. If usefulness, rather than the ability to use buzzwords (i.e. an empty "end-to-end") is the goal, then baking segmentation into the G2P task is an at least relatively bad idea. Similar to baking language detection into it, mind you... -->

- Add a pivot task (`ipa2ipa|from=en|to=sv`) to test if explicit bridging improves cross-language consistency.
  <!-- JE (supervisor): Ok so "add" is not really right, it's more been the primary goal all along? -->
  <!-- JOR: Right. Whether explicitly or via a pivot, a G2P that can directly handle foreign words according to a single language's phoneset is a relatively rare thing, so even if the pivot fails the fallback is still a win. -->

- Evaluate:
  - Zero-/few-shot G2P accuracy
  - Cross-language consistency
  - Evidence of shared phonological representations (embedding similarity)

### Data

#### Braxen

<!-- (same Braxen description as in main paper) -->

### ...

## Results

## Discussion

## Conclusion

<!-- In addition to the part of speech information also contained in Braxen, the NST lexicons include information about named entities, which is quite detailed in terms of category and subcategory. It also contains compound information, which is useful to the grapheme-to-phoneme process: the letter sequence 'sch' is a trigraph representing a single sound in 'dusch' (*shower*), but represents 's' and 'ch' in 'potatischips' (*potato chips*), for example. -->

<!-- Compounds in NST are split into their composite parts, including the linker: while it might be more correct in terms of compounds to think of the linking 's' as a separate entity, rather than treating it as part of the noun (usually, making it identical to the genitive form), for the purposes of syllabification, it is preferable to keep this 's' attached to the correct noun: e.g., "Östermalmstorg" ought to be syllabified in terms of "Östermalms" + "torg", not "Östermalm" + "*storg". -->

<!-- This particular example demonstrates a limitation with our method: "Östermalm" itself is a compound: "öster" + "malm" (*east suburb*), but this cannot be recovered from the Braxen data, as the transcription lacks a compound marker. This is, however, likely to be preferable for other purposes: none of the compounds that contain it refer to anything other than the place. -->

<!-- Although the named entity information is less information for our purposes, we choose to maintain it; our conversion of the NST data is complete, though modernised. First, the data has been converted to Unicode; transcriptions, which occupied a fixed number of fields in the original data, have been converted to a list structure; finally, in addition to maintaining the original transcription, we also add an IPA conversion: although the transcriptions are claimed to use SAMPA, in reality the original transcriptions are rather loosely based on SAMPA. -->

## Acknowledgements

## References
