---
title: "Multilingual G2P with Phonetisaurus"
bibliography: references.bib
---

## Introduction

Text to speech (TTS) systems are typically built to use phones rather than raw text. Even for languages with shallow orthographies, the relationship between the written and spoken form is often indirect, so phones act as an intermediary that are intended to ensure the correct sounds are produced.

Pronunciation dictionaries are often hard to find, and are never complete in a living language. For this reason, the task of grapheme to phoneme (G2P) conversion exists: to automate the production of a phonetic representation of words not in the dictionary.

Grapheme-to-phoneme (G2P) conversion is typically considered in terms of a single language, but languages do not exist in isolation: words, names in particular, from other languages make frequent appearances.

While monolingual G2P systems perform well within their target language, they struggle to adapt to words borrowed from other languages. Unassimilated loanwords follow the rules of their source language, and can even have a negative impact on the source language if too many are introduced into the training data of a G2P system, by introducing confusion. For instance, even state-of-the-art end-to-end TTS systems such as DiTTo-TTS [@lee2025dittotts] occasionally mispronounce words from well-resourced languages like Polish, despite large multilingual datasets.

A further complication arises from how text is marked up for synthesis. Standards such as the Speech Synthesis Markup Language (SSML) [@w3c:ssml11] permit the explicit specification of language on multiple levels---paragraph, sentence, or word---but these annotations are only useful if the G2P component itself can interpret them correctly.

In this work, we explore the extent to which multilingual or mixed-language G2P training improves---or degrades---performance across languages. Using the Braxen lexicon [@tannander-edlund-2025-braxen], a Swedish TTS resource containing extensive foreign-language entries, we compare monolingual, multilingual, and untagged models to quantify how cross-language exposure affects phoneme error rate (PER). Our goal is to better understand how multilingual data and language tagging influence pronunciation accuracy in practical TTS systems.

## Background

Recent work in text to speech (TTS), such as @gao2023e3tts, attempts to move towards "end to end" synthesis, without the use of a phonetic transcription. As impressive as they are, they do not always pronounce everything correctly: on the samples page[^ditto] for DiTTo-TTS [@lee2025dittotts], for example, in the second Polish example the word "niektórzy" is mispronounced: Polish has quite a shallow orthography and a relatively large amount of publicly available data.

[^ditto]: <https://ditto-tts.github.io/>

Speech Synthesis Markup Language (SSML) [@w3c:ssml11], the most widely used standard for representing to a TTS engine how a piece of text should be read, allows language to be specified on multiple levels, including paragraph, sentence, token, and word. This degree of control over generated speech is desirable in many contexts, particularly in contexts where the end-users rely on a spoken form, such as those with print difficulties.

One typical option for handling words of foreign origin is to perform a phoneset mapping, where the output of a G2P system for the other language is mapped to that of the current language. This requires a separate G2P component for each language individually, in addition to the mapping, which increases the complexity of the text processing pipeline.

<!-- In a rule-based paradigm, there are two common options for adapting a system designed for one language to the phoneset of another: either by editing the G2P rules themselves so that they output phones appropriate for the second language, or by explicitly mapping the phones it outputs to those of the other language. -->

### Data

#### Braxen

Braxen is an off-shoot of the internal TTS lexicon maintained by the Swedish Agency for Accessible Media (MTM), whose mission includes the production of material for people with print difficulties. This involves creating audiobooks and TTS services for news, so the lexicon is kept up to date with new vocabulary on an on-going basis.

As such, some of the vocabulary in Braxen reflects the realities of text "in the wild": it includes a large selection of words from other languages. From our perspective, the detail that is most interesting is that it includes language tags for these foreign words.

As MTM is primarily concerned with the practical matter of producing spoken forms of written material, rather than lexicography for its own sake, a number of errors and inconsistencies appear in the data in relation to the tagging of languages: the languages are tagged using a three-letter language code: in the case of Latin ('lat'), this is a single character away from the character codes of Latvian ('lav') and Lithuanian ('Lit'): consequently, we find a small number of words from those languages tagged as Latin.

By far the most represented foreign language in Braxen is English.
English is taught as a mandatory subject in schools across Sweden [@norrby2014english]: according to the 2024 Eurobarometer report, 90% of Swedes report feeling comfortably conversational in English [@eurobarometer2024languages], and according to the EF English Proficiency Index 2024, Swedes rank 4th in the world in terms of their English skills [@efepi2024].

In addition to being the primary languages of neighbouring countries, Danish, Swedish, and Norwegian form a dialect continuum, and there is some degree of mutual intelligibility between their speakers. As such, Danish and Norwegian words are among the best represented in Braxen. However, as reflects the nature of text in the wild, many of these words are spelled using Swedish letters: the Norwegian and Danish alphabets have the letters 'æ' and 'ø' where Swedish has 'ä' and 'ö', respectively, with 'æ' additionally rewritten as 'ae'.

## Method

As a first pass, we attempted to find misclassified words by checking for characters that are typical of the language each word was tagged as belonging to. For instance, Swedish words rarely contain the letters 'ç' or 'ñ', whereas these are common in French and Spanish, respectively. We compiled a list of such characteristic letters for each language represented in Braxen and used it to flag cases where the spelling and language tag appeared inconsistent. While this simple heuristic highlighted a number of misclassified words, it generated too much noise: very few of the characters in the languages represented in Braxen are truly unique to that language alone, and even when that is the case, there are too many instances of words with incorrect accents, such as 'à' instead of 'á' in Spanish.

We concentrated our efforts by selecting only languages with 1,000 or more entries; as a replacement form of filtering, we passed each candidate word to a spelling checker, selecting only those that were marked as correct. One clear limitation of this approach is for languages whose script is not Latin: the majority of words classified as Russian in Braxen are transliterated, which reduced the initial number of entries from 1,320 to just 7.

Another, somewhat surprising limitation of this approach was the limits of the spell checking dictionaries for certain languages. For Spanish, for example, a large number of proper names we know to be correct were simply absent from the default dictionary.

Of the initial set of languages, only English, Danish, French, Spanish, Italian, and Latin were retained.

For our comparisons, we trained G2P models using Phonetisaurus [@NOVAK_MINEMATSU_HIROSE_2016] in three configurations: individual models, one for each source language; a combined "raw" model, which mixes all vocabulary, regardless of origin; and a "merged" model, where non-Swedish words were given a prefix unique to that language.

In addition to these three configurations, we also tested the results of the merged model without providing the prefix. For each language and configuration, we calculated the phoneme error rate (PER). The results are in @tbl-per: **WL** refers to the individual models, **MWL** refers to the merged model tested with a language-specific prefix; **WLM** refers to the merged model tested without providing the prefix; and **RAW** refers to the model that combines all entries without any prefix.

## Results

| Language | WL | MWL | WLM | RAW | ΔMWL-WL (%) | ΔWLM-WL (%) | ΔRAW-WL (%) |
|----------|------|------|------|------|-------------|-------------|-------------|
| swe | 0.0099 | 0.0099 | -- | 0.0096 | 0.0 | -- | -3.0 |
| dan | 0.1099 | 0.1122 | 0.1393 | 0.1215 | +2.1 | +26.8 | +10.6 |
| eng | 0.1256 | 0.1566 | 0.2593 | 0.2113 | +24.7 | +106.5 | +68.2 |
| spa | 0.1094 | 0.1419 | 0.1641 | 0.1453 | +29.7 | +50.0 | +32.8 |
| lat | 0.1136 | 0.1329 | 0.1595 | 0.1422 | +17.0 | +40.4 | +25.2 |
| fre | 0.1687 | 0.2485 | 0.2983 | 0.2945 | +47.3 | +76.8 | +74.5 |
| ita | 0.1050 | 0.1196 | 0.1553 | 0.1553 | +13.8 | +47.9 | +47.9 |
| **Average** | **0.1060** | **0.1316** | **0.1960** | **0.1548** | **+24.2** | **+85.0** | **+46.1** |

: Phoneme Error Rates (PER) for individual and merged G2P models. Lower is better. {#tbl-per}

## Discussion

## Conclusion

<!-- In addition to the part of speech information also contained in Braxen, the NST lexicons include information about named entities, which is quite detailed in terms of category and subcategory. It also contains compound information, which is useful to the grapheme-to-phoneme process: the letter sequence 'sch' is a trigraph representing a single sound in 'dusch' (*shower*), but represents 's' and 'ch' in 'potatischips' (*potato chips*), for example. -->

<!-- Compounds in NST are split into their composite parts, including the linker: while it might be more correct in terms of compounds to think of the linking 's' as a separate entity, rather than treating it as part of the noun (usually, making it identical to the genitive form), for the purposes of syllabification, it is preferable to keep this 's' attached to the correct noun: e.g., "Östermalmstorg" ought to be syllabified in terms of "Östermalms" + "torg", not "Östermalm" + "*storg". -->

<!-- This particular example demonstrates a limitation with our method: "Östermalm" itself is a compound: "öster" + "malm" (*east suburb*), but this cannot be recovered from the Braxen data, as the transcription lacks a compound marker. This is, however, likely to be preferable for other purposes: none of the compounds that contain it refer to anything other than the place. -->

## Acknowledgements

## References
